config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

   root 'welcome#index'
   resources :welcome
   get 'show_coctaile' => "welcome#show_coctaile"

     namespace :admin do
       root 'welcome#show'
       resources :products
       resources :coctailes
       resources :ajax_products
     end
end

app/models/coctaile.rb
class Coctaile < ActiveRecord::Base

  mount_uploader :image, CoctaileImageUploader

  has_many :ingredients
  has_many :products, through: :ingredients

  before_save { self.name = name.titleize}
  before_save  :set_alcohol_status!

  enum alcoholic:[:alcohol, :unalcohol]

  validates :name, presence: true, allow_blank: false

  validate :validate_coctaile

  accepts_nested_attributes_for :ingredients,
    reject_if: lambda { |attributes|
       attributes[:value].blank? && attributes[:product_id].blank? }

  def validate_coctaile
    drink = 0
    equal_products = 0
    ingredients.select{ |ingredient|
      if ingredient.product.present?
        if ingredient.product.product_type == 'drink'
          drink = drink + 1
        end
      end

      ingredients.each do |ingredient_p|
        if ingredient_p.product_id == ingredient.product_id
          equal_products = equal_products + 1
        end
      end
    }


    if drink < 1
      errors.add(:coctaile, " must have more drinks")
    end
    if ingredients.size == 1
      errors.add(:coctaile, " must have more ingredients")
    end
    if equal_products > ingredients.size
      errors.add(:coctaile, " can't have equal products")
    end
  end


  def value
    ingredients.inject(0) { |sum, ingredient|
      sum + (ingredient.product.product_type == 'drink' ? ingredient.value : 0)
    }
  end

  def price
    ingredients.inject(0) { |price, ingredient|
      price + (ingredient.value / ingredient.product.min_value) *
        ingredient.product.price
    }
  end

private

  def set_alcohol_status!
    alc_ingredients = ingredients.select{ |ingredient|
        ingredient.product.have_alc?
    }
    self.have_alc = alc_ingredients.size > 0 ? 1 : 0

  end


end

app/controllers/admin/coctailes_controller.rb
class Admin::CoctailesController < Admin::ApplicationController

  INGREDIENT_MAX_COUNT = 5

  before_filter :find_item, only: [:edit, :update, :destroy, :show]

  def prepare_ingredient_items
    (INGREDIENT_MAX_COUNT - @coctaile.ingredients.count).times{
      @coctaile.ingredients.build
    }
  end

  def index
    @coctailes = Coctaile.includes(:ingredients, :products)
  end

  def new
    @coctaile = Coctaile.new
    prepare_ingredient_items
  end

  def create
    @coctaile = Coctaile.create item_params
    if @coctaile.errors.empty?
      flash[:success] = "Coctaile \'#{@coctaile.name.humanize}\' was created successfully"
      redirect_to action: 'index'
    else
      flash[:warning] = @coctaile.errors.full_messages.to_sentence
      render :new
    end
  end

  def item_params
    params.require(:coctaile).permit(:id, :name, :image, :value, ingredients_attributes: [:id, :value, :product_id, :coctaile_id])
  end

  def edit
    prepare_ingredient_items
  end

  def destroy
    @coctaile.destroy
    redirect_to action: 'index'
  end

  def update
    @coctaile.update_attributes item_params
    if @coctaile.errors.empty?
      redirect_to action: :index
    else
      prepare_ingredient_items
      render :edit
    end
  end

  def find_item
    @coctaile = Coctaile.where(id: params[:id]).first
  end

end

app/controllers/coctailes_controller.rb
class CoctailesController < ApplicationController

  INGREDIENT_MAX_COUNT = 5

  before_filter :find_item, only: [:edit, :update, :destroy, :show]

  def prepare_ingredient_items
    (INGREDIENT_MAX_COUNT - @coctaile.ingredients.count).times{
      @coctaile.ingredients.build
    }
  end

  def index
    @coctailes = Coctaile.all
  end

  def new
    @coctaile = Coctaile.new
    prepare_ingredient_items
  end

  def create
    @coctaile = Coctaile.create item_params
    if @coctaile.errors.empty?
      flash[:success] = "Coctaile \'#{@coctaile.name.humanize}\' was created successfully"
      redirect_to @coctaile
    else
      flash[:warning] = @coctaile.errors.full_messages.to_sentence
      render :new
    end
  end

  def item_params
    params.require(:coctaile).permit(:id, :name,:image, ingredients_attributes: [:id, :value, :product_id, :coctaile_id])
  end

  def edit
    prepare_ingredient_items
  end

  def destroy
    @coctaile.destroy
    redirect_to action: 'index'
  end

  def update
    @coctaile.update_attributes item_params
    if @coctaile.errors.empty?
      redirect_to action: :index
    else
      prepare_ingredient_items
      render :edit
    end
  end

  def find_item
    @coctaile = Coctaile.where(id: params[:id]).first
  end

end

app/helpers/coctailes_helper.rb
module CoctailesHelper

  def form_ingredients(form_builder, field_name_num, field_name_col, method, collection, value_method, text_method, options = {}, html_options = {})
    form_builder.fields_for :ingredients do |form_builder|
      "<div class='field form-group'>
        <div class='field form-group'>
           #{form_field_row_collection_select(form_builder,field_name_col, method, collection, value_method, text_method, options, html_options)}
           #{form_field_row_numeric(form_builder, field_name_num)}
        </div>
     </div>".html_safe
    end
  end

end

app/views/admin/coctailes/_form.html.erb
<div class="body_panel panel-default">
  <div class="panel-body">
    <%= form_field_text(f, :name) %>
    <div class="row form-group">
      <div class="col-sm-3"><%= image_tag(@coctaile.image_url, size: '280', class: "img-thumbnail") if @coctaile.image? %></div>
      <div class="col-sm-9 form-group">
        <div class="field form-group">
          <%= f.label "Ingredients:" %>
        </div>
        <%= form_ingredients(f, :value, :product,:product_id, Product.all, :id, :name, {prompt: true}, {}) %>
       </div>
    </div>
    <div class="field form-group">
      <%= f.label :image, class: "col-md-2 control-label" %>
      <div class="col-sm-3">
        <%= f.file_field :image, multiple: false %>
      </div>
    </div>
    <% if @coctaile.image? %>
        <div class="field form-group">
          <div class="col-md-2 control-label"></div>
          <div class="col-sm-5">
            <%= f.check_box :remove_image %> Remove image
          </div>
        </div>
    <% end %>
  </div>
</div>
<div class="actions form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit "Save" %>
  </div>
</div>

app/views/admin/coctailes/edit.html.erb
<%= render partial: 'layouts/partials/header' %>
<%= form_for @coctaile, url: {action: 'update'} do |f| %>
    <%= render partial: 'form', locals: {f: f}%>
<% end %>

app/views/admin/coctailes/index.html.erb
<%= render partial: 'layouts/partials/header' %>
<% if @coctailes.empty? %>
    <h2>Coctailes list is empty</h2>

<% else %>
    <table>
      <tr>
        <th>Id</th>
        <th>Product Name</th>
        <th>Value</th>
        <th>Price</th>
        <th>Have_alcohol</th>
        <th>Edit</th>
        <th>Remove</th>
      </tr>

      <% @coctailes.each do |coctaile| %>
        <tr>
          <td><%= coctaile.id %></td>
          <td><%= link_to coctaile.name, admin_coctaile_path(coctaile) %></td>
          <td><%= coctaile.value %></td>
          <td><%= coctaile.price %></td>
          <td><%= coctaile.alcoholic %></td>
          <td><%= link_to 'edit', edit_admin_coctaile_path(coctaile) %></td>
          <td><%= link_to 'remove', admin_coctaile_path(coctaile), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </table>
 <% end %>
<%= link_to 'New_Coctaile', new_admin_coctaile_path(@coctaile) %>

app/views/admin/coctailes/new.html.erb
<%= render partial: 'layouts/partials/header' %>
<%= form_for @coctaile, url: {action: 'create'} do |f| %>
    <%= render partial: 'form', locals: {f: f}%>
<% end %>

app/views/admin/coctailes/show.html.erb
<%= render partial: 'layouts/partials/header' %>
<ul>
  <li><%= "ID: #{@coctaile.id}" %></li>
  <li><%= "Name: #{@coctaile.name}" %></li>
  <li><%= "Min value: #{@coctaile.value}" %></li>
  <li><%= "Cost price: #{@coctaile.price}" %></li>
  <li><%= "Have alcohol: #{@coctaile.have_alc}" %></li>
</ul>
<p>Ingredients</p>
  <hr>
<ul>
    <% @coctaile.ingredients.each do |ingredient| %>
      <li><%= "#{ingredient.product.name} #{ingredient.value}" %></li>
    <% end %>
</ul>